services:
  - type: web
    name: eterna-backend
    env: node
    plan: free
    buildCommand: npm ci && npx prisma generate && npx prisma migrate deploy
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: JWT_REFRESH_EXPIRES_IN
        value: 30d
      - key: CORS_ORIGIN
        value: https://eterna-frontend.onrender.com
      - key: ENABLE_SWAGGER
        value: false
      - key: THROTTLE_TTL
        value: 60
      - key: THROTTLE_LIMIT
        value: 100
      - key: BCRYPT_ROUNDS
        value: 12
      - key: HELMET_ENABLED
        value: true
      - key: COMPRESSION_ENABLED
        value: true
      - key: LOG_LEVEL
        value: info
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: eterna-postgres
    databaseName: eterna_db
    user: eterna_user
    plan: free
