services:
  - type: web
    name: eterna-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: file:./eterna.db
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: "*"
      - key: ENABLE_SWAGGER
        value: false
      - key: THROTTLE_TTL
        value: 60
      - key: THROTTLE_LIMIT
        value: 100
      - key: LOG_LEVEL
        value: info
      - key: BCRYPT_ROUNDS
        value: 12
      - key: HELMET_ENABLED
        value: true
      - key: COMPRESSION_ENABLED
        value: true
